export const BOOKS_LIST_REQUEST = "BOOKS_LIST_REQUEST";
export const BOOKS_LIST_SUCCESS = "BOOKS_LIST_SUCCESS";
export const BOOKS_LIST_FAILURE = "BOOKS_LIST_FAILURE";

export const SELECT_PAGE = "SELECT_PAGE";
